# Numbers
NUM_TRIALS = 3
# Paths
IMG_FOLDER = 'img/'
DATA_FOLDER = 'data/'
# Times
FACE_TIME = 0.5
FIXATION_TIME_MIN = 1.5
FIXATION_TIME_MAX = 3.5
NUMBER_TIME = 0.5
MENTAL_NAV_TIME = [3.5, 5.5]
SELECTION_TIME = 0.4  # TODO ?
POST_SELECTION_TIME = 0.1  # TODO ???
FEEDBACK_TIME = 1.5
TRIAL_INTERVAL = [4, 6, 8]
# Strings
FEEDBACK_RIGHT = 'You got it'
FEEDBACK_WRONG = 'Wrong'
